language: ruby

rvm:
  - 2.3.1

gemfile:
  - Gemfile

before_install:
  - gem install bundler

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - bundle exec rake

branches:
  only:
    - master
